FROM mcr.microsoft.com/playwright:v1.49.0-jammy

WORKDIR /app

COPY package*.json ./
RUN npm install --only=production

COPY scraper-base.js ./
COPY scraper-nano.js ./
COPY scraper-heavy.js ./
COPY server.js ./

ENV PORT=8081
ENV SCRAPER_TYPE=heavy

EXPOSE 8081

CMD ["node", "server.js"]
